"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
var express_1 = require("express");
var CreateUserController_1 = require("./controllers/CreateUserController");
var CreateTagController_1 = require("./controllers/CreateTagController");
var EnsureAdmin_1 = require("./middlewares/EnsureAdmin");
var router = express_1.Router();
exports.router = router;
var createUserController = new CreateUserController_1.CreateUserController();
var createTagController = new CreateTagController_1.CreateTagController();
router.post("/users", createUserController.handle);
router.post("/tags", EnsureAdmin_1.ensureAdmin, createTagController.handle);
